#Ansible variables file
darkmode: false
development: false
homedir: "/home/{{ item.name }}"
my_ssh_key_file: "put explicit keyfile location here"
dotfiles_repo: git@github.com:waltdundore/dotfiles.git
dotfiles_destination: /home/wdundore/git/testdotfiles
